### PR TITLE
support multi-arch image

### PR DESCRIPTION
**Pull request by better0332**
support multi-arch image for linux/amd64,linux/arm64
issue: #147

### CODE REVIEW

**Comment by Hamidhasan** [comment]
Thank you for submitting the feature request to AWS Private CA Issuer plugin. We have reviewed your submission, and this feature request is not prioritized at this time. Currently we do not officially support ARM, our automation runs only for x86-64 based environments. We have captured your request as a potential enhancement for consideration on our roadmap.

In the interim, you are free to build the docker image and utilize it for your use case.

**Comment by irbekrm** [comment]
> Currently we do not officially support ARM, our automation runs only for x86-64 based environments.

FWIW, in cert-manager we also do not run e2e tests for all the platforms [we build for](https://github.com/cert-manager/cert-manager/blob/master/build/platforms.bzl#L22-L26) and I believe other projects take a similar approch.

**Comment by ghostsquad** [comment]
It's now 2024, any chance this can be rebased and merged?

**Comment by bmsiegel** [comment]
Completed by #319, you can access the ARM version of this issuer on v1.3.0 or above

**Pull request closed without merging**
