### PR TITLE
Add support for certificate usages with templateARN

### PR DESCRIPTION
**Pull request by marshields**
Fixes https://github.com/cert-manager/aws-privateca-issuer/issues/19

Signed-off-by: marshields <78823471+marshields@users.noreply.github.com>

### CODE REVIEW

**Comment by paramsethi** [comment]
The template arns can be different in gov regions, for example as called out here: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html

We should fix the hard coded values to reflect the aws partition based on current region.

For example: 
arn:aws:acm-pca:::template/CodeSigningCertificate/V1 
vs 
arn:aws-us-gov:acm-pca:::template/CodeSigningCertificate/V1

**Comment by marshields** [comment]
> The template arns can be different in gov regions, for example as called out here: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html
> 
> We should fix the hard coded values to reflect the aws partition based on current region.
> 
> For example:
> arnawsacm-pca:::template/CodeSigningCertificate/V1
> vs
> arn:aws-us-gov:acm-pca:::template/CodeSigningCertificate/V1

Thanks for pointing that out. We've changed our implementation to handle that use case.

@jniebuhr, can you please review?

**Review by paramsethi — CHANGES_REQUESTED** [review]
Thanks for the updated PR. Can we change the prefix to always come from CA Arn, where we split the arn till second ":", and use that for template prefix? This way, if AWS ever decides to add more partitions in the near future, the code will continue to work.

**Comment by paramsethi** [comment]
Sorry, I was out on vacation and did not get a chance to look at this PR. Can you please look at the comment? Otherwise, changes look good.

**Comment by marshields** [comment]
> Thanks for the updated PR. Can we please change the prefix to always come from CA Arn, where we split the arn till second ":", and use that for template prefix? This way, if AWS ever decides to add more partitions in the near future, the code will continue to work. Thanks!

Sure thing, we just added. Can you re-review/approve?

**Review by paramsethi — APPROVED** [review]

**Comment by laebshade** [comment]
Thank you @paramsethi

**Pull request merged**
