### PR TITLE
Added ability to set env vars to enable use cases such as http/https_…

### PR DESCRIPTION
**Pull request by eperdeme**
Added helm chart env vars option, so users can specify proxy servers if needed.

### CODE REVIEW

**Comment by pmcgrath** [comment]
Also waiting on this PR, would be great to get in a release

**Comment by divyansh-gupta** [comment]
Hi @eperdeme this looks great, thanks for this contribution. Final thing: could you please add to the e2e tests to make sure this functionality is tested?

**Comment by eperdeme** [comment]
> Hi @eperdeme this looks great, thanks for this contribution. Final thing: could you please add to the e2e tests to make sure this functionality is tested?

I'll give it a good go.

Just to clarify, is the e2e test to verify that an ENV var being defined is present on the pod (env | grep MYVAR), or that the app is able to consume a proxy server (as then we'd need a proxy server).

**Comment by eperdeme** [comment]
The issue with the tests is they spawn 2 CA's which from my understanding would incur a $800 fee, I'm not 100% sure how the "prorated" billing works, if they bill you $800 then refund you next month? Or they divide the $800/hours per month * hours of usage, but with that lack of understanding and clarify on AWS website I can't get financial signoff in my company to run the tests.

Either way, I think that's really going to put off anybody running these tests.

I'll comment out them element that spawn the PCA and just verify the ENV vars appear, but I can't run an E2E.

**Comment by eperdeme** [comment]
Further investigating shows the test pack to be dangerous. Whilst it does spawn the KinD cluster it doesn't change kubectl context to it, as such the first thing that happens is it destroys your defaulted kubectl context.

I think there's a fair amount of work needed outside of this MR to make the testing possible/functional for the community to contribute. As rewriting the test approach for the project is probably something I've not got the experience with and at current time to do.

It's up to you if you will accept the merge without the tests, for now we'll use the fork.

**Comment by divyansh-gupta** [comment]
Thanks for your feedback and questions. The CA pricing is pro-rated, so if a CA is deleted, AWS no longer charges for it. We have passed on your additional ideas on making contributions to this repository more accessible. If you choose to re-open this PR, we will be happy to consider reviewing and merging in your changes.

**Pull request closed without merging**
