### PR TITLE
Added environment variables to helm chart, as well as updated Makefil…

### PR DESCRIPTION
**Pull request by bmsiegel**
…e to locally install the chart

Signed-off-by: Brady Siegel <brsiegel@amazon.com>

### CODE REVIEW

**Comment by bmsiegel** [comment]
Here's an example log of running it adding the env variable

`helm install -f values_test.yaml --debug issuer ./charts/aws-pca-issuer -n aws-privateca-issuer \
--set serviceAccount.create=false --set serviceAccount.name=aws-privateca-issuer-sa \
--set image.repository="localhost:5000/aws-privateca-issuer" --set image.tag=latest --set image.pullPolicy=Always
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/charts/aws-pca-issuer

client.go:128: [debug] creating 1 resource(s)
install.go:146: [debug] CRD awspcaclusterissuers.awspca.cert-manager.io is already present. Skipping.
client.go:128: [debug] creating 1 resource(s)
install.go:146: [debug] CRD awspcaissuers.awspca.cert-manager.io is already present. Skipping.
client.go:128: [debug] creating 6 resource(s)
NAME: issuer
LAST DEPLOYED: Mon Nov 15 21:49:25 2021
NAMESPACE: aws-privateca-issuer
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
env:
  http_proxy: http://corpproxy:3128
  https_proxy: http://corpproxy:3128
  no_proxy: localhost.127.0.0.1,instance-data,10.0.0.0/8,169.254.169.254,100.64.0.0/10,.corptld.plc
image:
  pullPolicy: Always
  repository: localhost:5000/aws-privateca-issuer
  tag: latest
serviceAccount:
  create: false
  name: aws-privateca-issuer-sa

COMPUTED VALUES:
affinity: {}
approverRole:
  enabled: true
  namespace: cert-manager
  serviceAccountName: cert-manager
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
disableApprovedCheck: false
env:
  http_proxy: http://corpproxy:3128
  https_proxy: http://corpproxy:3128
  no_proxy: localhost.127.0.0.1,instance-data,10.0.0.0/8,169.254.169.254,100.64.0.0/10,.corptld.plc
fullnameOverride: ""
image:
  pullPolicy: Always
  repository: localhost:5000/aws-privateca-issuer
  tag: latest
imagePullSecrets: []
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
  runAsUser: 65532
rbac:
  create: true
replicaCount: 1
resources: {}
securityContext:
  allowPrivilegeEscalation: false
service:
  port: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: aws-privateca-issuer-sa
serviceMonitor:
  annotations: {}
  create: false
tolerations: []

HOOKS:
MANIFEST:
---
# Source: aws-privateca-issuer/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: issuer-aws-privateca-issuer
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
      - coordination.k8s.io
    resources:
      - configmaps
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaclusterissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaclusterissuers/finalizers
    verbs:
      - update
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaclusterissuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaissuers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaissuers/finalizers
    verbs:
      - update
  - apiGroups:
      - awspca.cert-manager.io
    resources:
      - awspcaissuers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests/status
    verbs:
      - get
      - patch
      - update
---
# Source: aws-privateca-issuer/templates/rbac.yaml
# permissions to approve all awspca.cert-manager.io requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:awspca-cert-manager-io
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - cert-manager.io
    resources:
    - signers
    verbs:
    - approve
    resourceNames:
    - awspcaclusterissuers.awspca.cert-manager.io/*
    - awspcaissuers.awspca.cert-manager.io/*
---
# Source: aws-privateca-issuer/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: issuer-aws-privateca-issuer
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: issuer-aws-privateca-issuer
subjects:
  - kind: ServiceAccount
    name: aws-privateca-issuer-sa
    namespace: aws-privateca-issuer
---
# Source: aws-privateca-issuer/templates/rbac.yaml
# bind the approver ServiceAccount to approve all awspca.cert-manager.io
# CertificateRequests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:awspca-cert-manager-io
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-approve:awspca-cert-manager-io
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
# Source: aws-privateca-issuer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: issuer-aws-privateca-issuer
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
---
# Source: aws-privateca-issuer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuer-aws-privateca-issuer
  labels:
    helm.sh/chart: aws-privateca-issuer-0.1.2
    app.kubernetes.io/name: aws-privateca-issuer
    app.kubernetes.io/instance: issuer
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-privateca-issuer
      app.kubernetes.io/instance: issuer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-privateca-issuer
        app.kubernetes.io/instance: issuer
    spec:
      serviceAccountName: aws-privateca-issuer-sa
      securityContext:
        runAsUser: 65532
      containers:
        - name: aws-privateca-issuer
          securityContext:
            allowPrivilegeEscalation: false
          image: "localhost:5000/aws-privateca-issuer:latest"
          imagePullPolicy: Always
          command:
            - /manager
          args:
            - --leader-elect
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: http_proxy
              value: "http://corpproxy:3128"
            - name: https_proxy
              value: "http://corpproxy:3128"
            - name: no_proxy
              value: "localhost.127.0.0.1,instance-data,10.0.0.0/8,169.254.169.254,100.64.0.0/10,.corptld.plc"
          resources:
            {}
      terminationGracePeriodSeconds: 10`

**Comment by bmsiegel** [comment]
Here's example of it failing on a bad deployment.yaml file

`helm install -f values_test.yaml --debug aws-pca-issuer ./charts/aws-pca-issuer -n aws-privateca-issuer \
--set serviceAccount.create=false --set serviceAccount.name=aws-privateca-issuer-sa \
--set image.repository="localhost:5000/aws-privateca-issuer" --set image.tag=latest --set image.pullPolicy=Always
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/charts/aws-pca-issuer

client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 1 resource(s)
install.go:160: [debug] Clearing discovery cache
wait.go:47: [debug] beginning wait for 2 resources with timeout of 1m0s
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "env" in io.k8s.api.apps.v1.DeploymentSpec
helm.go:88: [debug] error validating "": error validating data: ValidationError(Deployment.spec): unknown field "env" in io.k8s.api.apps.v1.DeploymentSpec
helm.sh/helm/v3/pkg/kube.scrubValidationError
        helm.sh/helm/v3/pkg/kube/client.go:622
helm.sh/helm/v3/pkg/kube.(*Client).Build
        helm.sh/helm/v3/pkg/kube/client.go:195
helm.sh/helm/v3/pkg/action.(*Install).Run
        helm.sh/helm/v3/pkg/action/install.go:263
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:242
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        helm.sh/helm/v3/pkg/action/install.go:265
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:242
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.1.3/command.go:852
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.1.3/command.go:897
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
        runtime/proc.go:225
runtime.goexit
        runtime/asm_amd64.s:1371
make: *** [install-local] Error 1`

**Comment by bmsiegel** [comment]
e2e output

```
make e2etest
mkdir -p /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin
test -f /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin/setup-envtest.sh || curl -sSLo /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.7.0/hack/setup-envtest.sh
source /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin/setup-envtest.sh; fetch_envtest_tools /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin; setup_envtest_env /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin; go test -v ./e2e/... -coverprofile cover.out
Using cached envtest tools from /workplace/brsiegel/PCA-Issuer/aws-privateca-issuer/testbin
setting up env vars
2021/11/16 18:25:42 Created RSA CA with arn arn:aws:acm-pca:us-east-1:718389859439:certificate-authority/5d4d532e-0988-4fca-9c7f-f86390eefa61
2021/11/16 18:25:49 Created EC CA with arn arn:aws:acm-pca:us-east-1:718389859439:certificate-authority/573af0df-d5e6-4cbf-8ab2-3c7c4cabf604
2021/11/16 18:25:49 Cross account role not present in PLUGIN_CROSS_ACCOUNT_ROLE, skipping cross account testing
2021/11/16 18:25:49 Created User CMUser1637087149 with policy arn arn:aws:iam::718389859439:policy/CMPolicy1637087149
=== RUN   TestClusterIssuers
2021/11/16 18:25:49 ----------
2021/11/16 18:25:49 Testing issuer: 1637087149--rsa-issuer
2021/11/16 18:25:49 Testing Certificate 1637087149--rsa-issuer-ec-cert
2021/11/16 18:25:53 Testing Certificate 1637087149--rsa-issuer-rsa-cert
2021/11/16 18:25:53 Testing Certificate 1637087149--rsa-issuer-rsa-cert-low-validity
2021/11/16 18:25:57 ----------
2021/11/16 18:25:57 Testing issuer: 1637087149--rsa-issuer-secret
2021/11/16 18:25:57 Testing Certificate 1637087149--rsa-issuer-secret-ec-cert
2021/11/16 18:26:01 Testing Certificate 1637087149--rsa-issuer-secret-rsa-cert
2021/11/16 18:26:01 Testing Certificate 1637087149--rsa-issuer-secret-rsa-cert-low-validity
2021/11/16 18:26:08 ----------
2021/11/16 18:26:08 Testing issuer: 1637087149--ec-issuer
2021/11/16 18:26:08 Testing Certificate 1637087149--ec-issuer-ec-cert
2021/11/16 18:26:08 Testing Certificate 1637087149--ec-issuer-rsa-cert
2021/11/16 18:26:15 Testing Certificate 1637087149--ec-issuer-rsa-cert-low-validity
2021/11/16 18:26:19 ----------
2021/11/16 18:26:19 Testing issuer: 1637087149--ec-issuer-secret
2021/11/16 18:26:19 Testing Certificate 1637087149--ec-issuer-secret-ec-cert
2021/11/16 18:26:19 Testing Certificate 1637087149--ec-issuer-secret-rsa-cert
2021/11/16 18:26:26 Testing Certificate 1637087149--ec-issuer-secret-rsa-cert-low-validity
--- PASS: TestClusterIssuers (37.31s)
=== RUN   TestNamespaceIssuers
2021/11/16 18:26:26 ----------
2021/11/16 18:26:26 Testing issuer: 1637087186--rsa-issuer
2021/11/16 18:26:26 Testing Certificate 1637087186--rsa-issuer-ec-cert
2021/11/16 18:26:33 Testing Certificate 1637087186--rsa-issuer-rsa-cert
2021/11/16 18:26:37 Testing Certificate 1637087186--rsa-issuer-rsa-cert-low-validity
2021/11/16 18:26:37 ----------
2021/11/16 18:26:37 Testing issuer: 1637087186--rsa-issuer-secret
2021/11/16 18:26:37 Testing Certificate 1637087186--rsa-issuer-secret-ec-cert
2021/11/16 18:26:44 Testing Certificate 1637087186--rsa-issuer-secret-rsa-cert
2021/11/16 18:26:48 Testing Certificate 1637087186--rsa-issuer-secret-rsa-cert-low-validity
2021/11/16 18:26:48 ----------
2021/11/16 18:26:48 Testing issuer: 1637087186--ec-issuer
2021/11/16 18:26:48 Testing Certificate 1637087186--ec-issuer-ec-cert
2021/11/16 18:26:55 Testing Certificate 1637087186--ec-issuer-rsa-cert
2021/11/16 18:26:55 Testing Certificate 1637087186--ec-issuer-rsa-cert-low-validity
2021/11/16 18:27:02 ----------
2021/11/16 18:27:02 Testing issuer: 1637087186--ec-issuer-secret
2021/11/16 18:27:02 Testing Certificate 1637087186--ec-issuer-secret-ec-cert
2021/11/16 18:27:03 Testing Certificate 1637087186--ec-issuer-secret-rsa-cert
2021/11/16 18:27:09 Testing Certificate 1637087186--ec-issuer-secret-rsa-cert-low-validity
--- PASS: TestNamespaceIssuers (46.77s)
PASS
coverage: 46.0% of statements
2021/11/16 18:27:13 Deleted the RSA CA
2021/11/16 18:27:13 Deleted the EC CA
2021/11/16 18:27:13 Deleted the Access Key
2021/11/16 18:27:13 Deleted the User and associated policy
ok      github.com/cert-manager/aws-privateca-issuer/e2e        98.542s coverage: 46.0% of statements
```

**Review by anbaig — APPROVED** [review]

**Pull request merged**
