### PR TITLE
fix: hpa v2 api update

### PR DESCRIPTION
**Pull request by bbensky**

### CODE REVIEW

**Comment by bbensky** [comment]
There have been a couple similar PRs for this the were never merged in, so just trying to get this finished up:
https://github.com/cert-manager/aws-privateca-issuer/pull/290
https://github.com/cert-manager/aws-privateca-issuer/pull/306

**Comment by bmsiegel** [comment]
https://github.com/cert-manager/aws-privateca-issuer/actions/runs/10406379982/job/28819337862?pr=335

**Comment by bbensky** [comment]
> Testing failed: https://github.com/cert-manager/aws-privateca-issuer/actions/runs/10406379982/job/28819337862?pr=335

Fixed.

**Comment by bmsiegel** [comment]
Looks like the testing passed. Thanks for the fix. Would you mind squashing these commits into the same one? Will get it merged after that.

**Comment by bbensky** [comment]
@bmsiegel Is it possible to run that failed test again? Looks like it failed testing one specific cert.

**Pull request merged**
